# Generated by Django 4.2.9 on 2024-02-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uservideo",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="uservideo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2022-10-25 12:58"),
            preserve_default=False,
        ),
    ]
