# Generated by Django 4.2.9 on 2024-01-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="Date of birth"),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=255, null=True, verbose_name="First name of User"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="height",
            field=models.PositiveIntegerField(null=True, verbose_name="Height"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=255, null=True, verbose_name="Last name of User"),
        ),
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.CharField(
                choices=[("beginner", "beginner"), ("intermediate", "intermediate"), ("advanced", "advanced")],
                max_length=20,
                null=True,
                verbose_name="Proficiency level",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="months_of_experience",
            field=models.IntegerField(null=True, verbose_name="Number of months of experience"),
        ),
        migrations.AddField(
            model_name="user",
            name="powerlifting_section",
            field=models.CharField(max_length=50, null=True, verbose_name="Powerlifting section"),
        ),
        migrations.AddField(
            model_name="user",
            name="weight",
            field=models.FloatField(null=True, verbose_name="Weight"),
        ),
    ]
