# Generated by Django 4.2.9 on 2024-02-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_birth_date_user_first_name_user_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="terms_confirmed",
            field=models.BooleanField(null=True),
        ),
    ]
